---
- name: Create the Demo environment on AAC
  hosts: localhost
  gather_facts: false
  vars:
    aws_local_ssh_key_file: "Replace with your aws local ssh key file path"
    automation_hub_url: "Replace with your API endpoint required to download certified content from Automation Hub"
    automation_hub_auth_url: "Replace wit your Authentication URL required to download content from Automation Hub"
    automation_hub_token: "Replace with your offline token"
    demo_scm_url: "https://github.com/yukshimizu/managing-rhel-lifecycle-demo" # Your git repository for demo contents

  vars_prompt:
    - name: aac_public_dns
      prompt: "Enter your AAC public dns name"
      private: false
    - name: aac_admin_passwd
      prompt: "Enter your AAC admin password"

  tasks:
    - name: Fetch private key
      ansible.builtin.slurp:
        src: "{{ aws_local_ssh_key_file }}"
      register: aws_ssh_key

    - name: Add aws_key credential
      awx.awx.credential:
        controller_host: "https://{{ aac_public_dns }}"
        controller_username: admin
        controller_password: "{{ aac_admin_passwd }}"
        name: aws_key
        credential_type: Machine
        organization: Default
        inputs:
          ssh_key_data: "{{ aws_ssh_key['content'] | b64decode }}"
        validate_certs: false

    - name: Add aws_cred credential
      awx.awx.credential:
        controller_host: "https://{{ aac_public_dns }}"
        controller_username: admin
        controller_password: "{{ aac_admin_passwd }}"
        name: aws_cred
        credential_type: "Amazon Web Services"
        organization: Default
        inputs:
          username: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
          password: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        validate_certs: false

    - name: Add automation_hub credential
      awx.awx.credential:
        controller_host: "https://{{ aac_public_dns }}"
        controller_username: admin
        controller_password: "{{ aac_admin_passwd }}"
        name: automation_hub
        credential_type: "Ansible Galaxy/Automation Hub API Token"
        organization: Default
        inputs:
          url: "{{ automation_hub_url }}"
          auth_url: "{{ automation_hub_auth_url }}"
          token: "{{ automation_hub_token }}"
        validate_certs: false

    - name: Add Galaxy credential to Default organization
      awx.awx.organization:
        controller_host: "https://{{ aac_public_dns }}"
        controller_username: admin
        controller_password: "{{ aac_admin_passwd }}"
        name: Default
        galaxy_credentials:
          - "Ansible Galaxy"
          - "automation_hub"
        validate_certs: false

    - name: Add Demo inventory
      awx.awx.inventory:
        controller_host: "https://{{ aac_public_dns }}"
        controller_username: admin
        controller_password: "{{ aac_admin_passwd }}"
        name: RHEL_Demo
        organization: Default
        state: present
        validate_certs: false

    - name: Add AWS inventory source to Demo inventory
      awx.awx.inventory_source:
        controller_host: "https://{{ aac_public_dns }}"
        controller_username: admin
        controller_password: "{{ aac_admin_passwd }}"
        name: AWS
        inventory: RHEL_Demo
        credential: aws_cred
        organization: Default
        source: "ec2"
        overwrite: true
        overwrite_vars: true
        update_on_launch: true
        source_vars:
          plugin: amazon.aws.aws_ec2
          keyed_groups:
            - prefix: tag
              key: tags
          regions:
            - ap-northeast-1
          filters:
            tag:purpose: demo
          strict_permissions: false
        validate_certs: false

    - name: Add Demo project
      awx.awx.project:
        controller_host: "https://{{ aac_public_dns }}"
        controller_username: admin
        controller_password: "{{ aac_admin_passwd }}"
        name: RHEL_Lifecycle_Demo
        organization: Default
        default_environment: "Default execution environment"
        scm_type: "git"
        scm_url: "{{ demo_scm_url }}"
        state: present
        validate_certs: false

    - name: Sync Demo project
      awx.awx.project_update:
        controller_host: "https://{{ aac_public_dns }}"
        controller_username: admin
        controller_password: "{{ aac_admin_passwd }}"
        project: RHEL_Lifecycle_Demo
        organization: Default
        timeout: 300
        validate_certs: false

    - name: Create "Content View Publish" job_template
      awx.awx.job_template:
        controller_host: "https://{{ aac_public_dns }}"
        controller_username: admin
        controller_password: "{{ aac_admin_passwd }}"
        name: "Content View Publish"
        job_type: "run"
        inventory: RHEL_Demo
        project: RHEL_Lifecycle_Demo
        playbook: publish_cv.yml
        state: present
        validate_certs: false

    - name: Create "Promote To Dev" job_template
      awx.awx.job_template:
        controller_host: "https://{{ aac_public_dns }}"
        controller_username: admin
        controller_password: "{{ aac_admin_passwd }}"
        name: "Promote To Dev"
        job_type: "run"
        inventory: RHEL_Demo
        project: RHEL_Lifecycle_Demo
        playbook: promote_cv.yml
        extra_vars:
          current_lce: Library
          target_lce: Development
        state: present
        validate_certs: false

    - name: Create "Backup Dev VM" job_template
      awx.awx.job_template:
        controller_host: "https://{{ aac_public_dns }}"
        controller_username: admin
        controller_password: "{{ aac_admin_passwd }}"
        name: "Backup Dev VM"
        job_type: "run"
        inventory: RHEL_Demo
        project: RHEL_Lifecycle_Demo
        playbook: snapshot_vm.yml
        credentials:
          - "aws_cred"
        extra_vars:
          managed_vms_environment: dev
        state: present
        validate_certs: false

    - name: Create "Update Dev VM" job_template
      awx.awx.job_template:
        controller_host: "https://{{ aac_public_dns }}"
        controller_username: admin
        controller_password: "{{ aac_admin_passwd }}"
        name: "Update Dev VM"
        job_type: "run"
        inventory: RHEL_Demo
        project: RHEL_Lifecycle_Demo
        playbook: update_vm.yml
        credentials:
          - "aws_key"
        extra_vars:
          target_hosts: tag_environment_dev
        state: present
        validate_certs: false

    - name: Create "Restart Dev VM" job_template
      awx.awx.job_template:
        controller_host: "https://{{ aac_public_dns }}"
        controller_username: admin
        controller_password: "{{ aac_admin_passwd }}"
        name: "Restart Dev VM"
        job_type: "run"
        inventory: RHEL_Demo
        project: RHEL_Lifecycle_Demo
        playbook: restart_vm.yml
        credentials:
          - "aws_cred"
        extra_vars:
          managed_vms_environment: dev
        state: present
        validate_certs: false

    - name: Create "Test Dev VM" job_template
      awx.awx.job_template:
        controller_host: "https://{{ aac_public_dns }}"
        controller_username: admin
        controller_password: "{{ aac_admin_passwd }}"
        name: "Test Dev VM"
        job_type: "run"
        inventory: RHEL_Demo
        project: RHEL_Lifecycle_Demo
        playbook: test_vm.yml
        credentials:
          - "aws_key"
        extra_vars:
          target_hosts: tag_environment_dev
        state: present
        validate_certs: false

    - name: Create "Test Dev App" job_template
      awx.awx.job_template:
        controller_host: "https://{{ aac_public_dns }}"
        controller_username: admin
        controller_password: "{{ aac_admin_passwd }}"
        name: "Test Dev App"
        job_type: "run"
        inventory: RHEL_Demo
        project: RHEL_Lifecycle_Demo
        playbook: test_app.yml
        credentials:
          - "aws_cred"
        extra_vars:
          managed_vms_environment: dev
        state: present
        validate_certs: false

    - name: Create "Promote To Prod" job_template
      awx.awx.job_template:
        controller_host: "https://{{ aac_public_dns }}"
        controller_username: admin
        controller_password: "{{ aac_admin_passwd }}"
        name: "Promote To Prod"
        job_type: "run"
        inventory: RHEL_Demo
        project: RHEL_Lifecycle_Demo
        playbook: promote_cv.yml
        extra_vars:
          current_lce: Development
          target_lce: Production
        state: present
        validate_certs: false

    - name: Create "Backup Prod VM" job_template
      awx.awx.job_template:
        controller_host: "https://{{ aac_public_dns }}"
        controller_username: admin
        controller_password: "{{ aac_admin_passwd }}"
        name: "Backup Prod VM"
        job_type: "run"
        inventory: RHEL_Demo
        project: RHEL_Lifecycle_Demo
        playbook: snapshot_vm.yml
        credentials:
          - "aws_cred"
        extra_vars:
          managed_vms_environment: prod
        state: present
        validate_certs: false

    - name: Create "Update Prod VM" job_template
      awx.awx.job_template:
        controller_host: "https://{{ aac_public_dns }}"
        controller_username: admin
        controller_password: "{{ aac_admin_passwd }}"
        name: "Update Prod VM"
        job_type: "run"
        inventory: RHEL_Demo
        project: RHEL_Lifecycle_Demo
        playbook: update_vm.yml
        credentials:
          - "aws_key"
        extra_vars:
          target_hosts: tag_environment_prod
        state: present
        validate_certs: false

    - name: Create "Restart Prod VM" job_template
      awx.awx.job_template:
        controller_host: "https://{{ aac_public_dns }}"
        controller_username: admin
        controller_password: "{{ aac_admin_passwd }}"
        name: "Restart Prod VM"
        job_type: "run"
        inventory: RHEL_Demo
        project: RHEL_Lifecycle_Demo
        playbook: restart_vm.yml
        credentials:
          - "aws_cred"
        extra_vars:
          managed_vms_environment: prod
        state: present
        validate_certs: false

    - name: Create "Test Prod VM" job_template
      awx.awx.job_template:
        controller_host: "https://{{ aac_public_dns }}"
        controller_username: admin
        controller_password: "{{ aac_admin_passwd }}"
        name: "Test Prod VM"
        job_type: "run"
        inventory: RHEL_Demo
        project: RHEL_Lifecycle_Demo
        playbook: test_vm.yml
        credentials:
          - "aws_key"
        extra_vars:
          target_hosts: tag_environment_prod
        state: present
        validate_certs: false

    - name: Create "Test Prod App" job_template
      awx.awx.job_template:
        controller_host: "https://{{ aac_public_dns }}"
        controller_username: admin
        controller_password: "{{ aac_admin_passwd }}"
        name: "Test Prod App"
        job_type: "run"
        inventory: RHEL_Demo
        project: RHEL_Lifecycle_Demo
        playbook: test_app.yml
        credentials:
          - "aws_cred"
        extra_vars:
          managed_vms_environment: prod
        state: present
        validate_certs: false

    - name: Create "Update Dev Environment" workflow_job_template
      awx.awx.workflow_job_template:
        controller_host: "https://{{ aac_public_dns }}"
        controller_username: admin
        controller_password: "{{ aac_admin_passwd }}"
        validate_certs: false
        name: "Update Dev Environment"
        inventory: RHEL_Demo
        survey_enabled: true
        survey_spec:
          description: ''
          name: "Survey for Dev Environment"
          spec:
            - choices: ''
              default: ''
              max: 1024
              min: 0
              new_question: true
              question_description: ''
              question_name: Enter ErrataByDate
              required: true
              type: text
              variable: foreman_cv_end_date
            - choices: ''
              default: ''
              max: 1024
              min: 0
              new_question: true
              question_description: ''
              question_name: Enter Satellite Password
              required: true
              type: text
              variable: foreman_admin_passwd
        workflow_nodes:
          - identifier: "Content View Publish"
            unified_job_template:
              name: "Content View Publish"
              organization:
                name: Default
              type: job_template
            related:
              success_nodes:
                - identifier: "Promote To Dev"
          - identifier: "Promote To Dev"
            unified_job_template:
              name: "Promote To Dev"
              organization:
                name: Default
              type: job_template
            related:
              success_nodes:
                - identifier: "Backup Dev VM"
          - identifier: "Backup Dev VM"
            unified_job_template:
              name: "Backup Dev VM"
              organization:
                name: Default
              type: job_template
            related:
              success_nodes:
                - identifier: "Update Dev VM"
          - identifier: "Update Dev VM"
            unified_job_template:
              name: "Update Dev VM"
              organization:
                name: Default
              type: job_template
            related:
              success_nodes:
                - identifier: "Restart Dev VM"
          - identifier: "Restart Dev VM"
            unified_job_template:
              name: "Restart Dev VM"
              organization:
                name: Default
              type: job_template
            related:
              success_nodes:
                - identifier: "Test Dev VM"
          - identifier: "Test Dev VM"
            unified_job_template:
              name: "Test Dev VM"
              organization:
                name: Default
              type: job_template
            related:
              success_nodes:
                - identifier: "Test Dev App"
          - identifier: "Test Dev App"
            unified_job_template:
              name: "Test Dev App"
              organization:
                name: Default
              type: job_template

    - name: Create "Update Prod Environment" workflow_job_template
      awx.awx.workflow_job_template:
        controller_host: "https://{{ aac_public_dns }}"
        controller_username: admin
        controller_password: "{{ aac_admin_passwd }}"
        validate_certs: false
        name: "Update Prod Environment"
        inventory: RHEL_Demo
        survey_enabled: true
        survey_spec:
          description: ''
          name: "Survey for Prod Environment"
          spec:
            - choices: ''
              default: ''
              max: 1024
              min: 0
              new_question: true
              question_description: ''
              question_name: Enter ErrataByDate
              required: true
              type: text
              variable: foreman_cv_end_date
            - choices: ''
              default: ''
              max: 1024
              min: 0
              new_question: true
              question_description: ''
              question_name: Enter Satellite Password
              required: true
              type: text
              variable: foreman_admin_passwd
        workflow_nodes:
          - identifier: "Promote To Prod"
            unified_job_template:
              name: "Promote To Prod"
              organization:
                name: Default
              type: job_template
            related:
              success_nodes:
                - identifier: "Backup Prod VM"
          - identifier: "Backup Prod VM"
            unified_job_template:
              name: "Backup Prod VM"
              organization:
                name: Default
              type: job_template
            related:
              success_nodes:
                - identifier: "Update Prod VM"
          - identifier: "Update Prod VM"
            unified_job_template:
              name: "Update Prod VM"
              organization:
                name: Default
              type: job_template
            related:
              success_nodes:
                - identifier: "Restart Prod VM"
          - identifier: "Restart Prod VM"
            unified_job_template:
              name: "Restart Prod VM"
              organization:
                name: Default
              type: job_template
            related:
              success_nodes:
                - identifier: "Test Prod VM"
          - identifier: "Test Prod VM"
            unified_job_template:
              name: "Test Prod VM"
              organization:
                name: Default
              type: job_template
            related:
              success_nodes:
                - identifier: "Test Prod App"
          - identifier: "Test Prod App"
            unified_job_template:
              name: "Test Prod App"
              organization:
                name: Default
              type: job_template
