---
# Minimal example using environment variables
# Fetch all hosts in ap-northeast
plugin: amazon.aws.aws_ec2
keyed_groups:
  - prefix: tag
    key: tags

# Change regions corresponding to your environment
regions:
  - ap-northeast-1 # adjust with your preference

# Filter only objects taged with "purpose" tag as "demo"
# filters:
#   tag:purpose: demo

# Ignores 403 errors rather than failing
strict_permissions: false
